name: docs

permissions:
  contents: write

on:
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: 20
          # cache deps for npm
          cache: npm

      # run build script
      - name: install deps
        run: npm i

      - name: prepack
        run: npm run prepack


      # run build script
      - name: Build VitePress site
        run: npm run docs:build

      - name: add nojekyll
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          > docs/.vitepress/dist/.nojekyll

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: docs/.vitepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
